SaniCenterWeb/Controllers/CajaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class CajaController : Controller
    {
        // GET: Caja
        public ActionResult Index()
        {
            int idpersona = Convert.ToInt32(Session["IdUsuario"]);
            if (idpersona == 0)
            {
                RedirectToAction("IniciarSesion", "Seguridad");
            }
            return View();
        }
        public ActionResult Facturación()
        {
          int idpersona = Convert.ToInt32(Session["IdUsuario"]);
          if (idpersona == 0)
            {
                RedirectToAction("IniciarSesion", "Seguridad");
            }
            return View();
        }
    }
}

SaniCenterWeb/Controllers/ComprasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class ComprasController : Controller
    {
        // GET: Compras
        public ActionResult Index()
        {
            return View();
        }
    }
}

SaniCenterWeb/Controllers/GenericController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Entidades;

namespace WebApplication2.Controllers
{
    public class GenericController : Controller
    {

        Negocio.EmpresaTiendaUsuario  objEmpresaTiendaUsuario =  new Negocio.EmpresaTiendaUsuario();
        // GET: Generic
        public ActionResult Index()
        {
            return View();
        }
        //public IEnumerable<System.Web.Mvc.SelectListItem> SelectEscalaTienda(string value)
        //{            
        //    List<Transportistas> Lista = transportistasBL.obtener_RazonsocialTransportistas();
        //    List<SelectListItem> data_list = new List<SelectListItem> { new SelectListItem() { Text = string.Format("[{0}]", "SELECCIONAR"), Value = "0" } };
        //    data_list.AddRange(Lista.OrderBy(a => a.Nombre_Transportista).Select(a => new SelectListItem() { Text = a.Nombre_Transportista.ToUpper(), Value = a.Nombre_Transportista }));

        //    if (value == "0") return new SelectList(data_list, "Value", "Text");
        //    else return new SelectList(data_list, "Value", "Text", value);
        //}
    }
}

SaniCenterWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Entidades;


namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        Negocio.AliasMant objAliasMant = new Negocio.AliasMant();
        Negocio.Documento objDocumento = new Negocio.Documento();
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";
            List<Entidades.AliasMant> listadoalias = objAliasMant.SelectAllActivo();
            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SaniCenterWeb/Controllers/SeguridadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Negocio;
using Entidades;
using Sani.Center.procces;
namespace WebApplication2.Controllers
{
    public class SeguridadController : Controller
    {
        public string idtienda;
        public int idcaja;
        public int idpersona;
        public int idperfil;

        SincronizacionSeguridad sincroseguridad = new SincronizacionSeguridad();

        // GET: Seguridad        
        public ActionResult Index()
        {            
            return View();
        }
        [HttpGet]
        public ActionResult IniciarSesion()
        {
            return View();
        }
        [HttpPost]
        public ActionResult IniciarSesionSanicenter()
        {
            Negocio.Usuario objusuario = new Negocio.Usuario();
            Util objutil = new Util();
            Negocio.Caja objcaja = new Negocio.Caja();
            Negocio.ParametroGeneral objparametro = new Negocio.ParametroGeneral();
            string usuario = Request.Form["user"].ToString();
            string password = Request.Form["password"].ToString();
          //  int idpersona = objusuario.ValidarIdentidad(usuario.Trim(), password.Trim());
           idpersona  = objusuario.ValidarIdentidad(usuario, password);
           idperfil = objusuario.ValidarIdentidadPerfil(usuario, password);
            if (idpersona!=0)
            {
                idtienda = objutil.ValidarTiendaxUsuario(idpersona);
                idcaja = objcaja.SelectIdCajaxIdPersona(idpersona);
                Session.Add("IdPersona", idpersona);
                Session.Add("IdUsuario", idpersona);
                Session.Add("IdCaja", idcaja);
                Session.Add("IdPerfil", idperfil);
                Session.Add("idTiendaUsuario", idtienda);
                //listaparametros = objparametro.getValorParametroGeneral();
            }
            else
            {
                return RedirectToAction("IniciarSesion", "Seguridad");
            }     
            
            return RedirectToAction("Index", "Home");
        }
    }
}

SaniCenterWeb/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class VentasController : Controller
    {
        // GET: Ventas
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult EmitirCotizacion()
        {
            return View();
        }
    }
}

SaniCenterWeb/Views/Caja/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

SaniCenterWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SaniCenterWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SaniCenterWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <img src="~/img/fondo.jpg" />
    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

SaniCenterWeb/Views/Seguridad/IniciarSesion.cshtml
@{
    Layout = null;
}


<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Style/style.css" rel="stylesheet" />
    <script>
        //$(document).ready(function ()
        //{
        //    "use strict";
        //    Login.init(); // Init login JavaScript
        //});
    </script>
</head>

<body>
    <div class="container">
        <div class="box-login">
            <div class="box-img">
                @*<img src="./img/React.js_logo.png" alt="">*@
            </div>
            <h2>Sanicenter Demo</h2>
            @using (Html.BeginForm("IniciarSesionSanicenter", "Seguridad", FormMethod.Post))
            {
            <form action="">
                <div class="inputBox">
                    <span class="logo-input">
                        <i class="fas fa-user"></i>
                    </span>
                    <input type="text" id="txtusuario" name="user" required />
                    <label for="">Usuario</label>
                </div>
                <div class="inputBox">
                    <span class="logo-input">
                        <i class="fas fa-key"></i>
                    </span>
                    <input type="password" id="txtpassword" name="password" required />
                    <label for="">Clave</label>
                </div>
                <div class="form-actions box-btn">                    
                    <button type="submit" class="btn">
                        Iniciar Sesion
                    </button>
                </div>                
                @*<div class="box-footer">
            <p>¿Aun no tienes cuenta?</p>
            <p>
                <b>¡Registrate!</b>
            </p>
        </div>*@
            </form>
            }
            </div>
    </div>
</body>

</html>

SaniCenterWeb/Views/Shared/_Conceptos.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Conceptos</h3>
                <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-3">
                        <a class="btn-danger">Ingresar Nuevo</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <label class="control-label">
                            Total Ingresado:
                        </label>
                    </div>
                    <div class="col-md-3">
                        S/.<input type="text" class="form-control" />                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SaniCenterWeb/Views/Shared/_Header.cshtml
@using Negocio;
@using Entidades;
@{
    int idpersona;
    idpersona = Convert.ToInt32(Session["IdUsuario"]);
    List<Opcion> listamenu = new List<Opcion>();
    List<Opcion> listamenucabecera = new List<Opcion>();
    List<Opcion> listadomenuitems = new List<Opcion>();
    if (idpersona != 0)
    {
        Negocio.Persona objpersona = new Negocio.Persona();
        Negocio.EmpresaTiendaUsuario objempresa = new Negocio.EmpresaTiendaUsuario();

        string descripcionpersona = objpersona.getDescripcionPersona(idpersona);
        //string fechaactual = Format((New Negocio.FechaActual).SelectFechaActual)

        string tienda = objempresa.fn_GetTiendaPrincipal(idpersona);
        //TRAER MENU DE USUARIO
        Negocio.opcion objopcion = new Negocio.opcion();
        listamenu = objopcion.SelectOpcionxUsuario(idpersona);
        listamenucabecera = listamenu.FindAll(a => a.IdMenu == 1);
        listadomenuitems = listamenu.FindAll(a => a.IdMenu !=1);
        //CARGAR TIPO CAMBIO SOLES Y DOLARES
    }
    else
    {
         @Url.Action("IniciarSesion", "Seguridad");
    }

}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Style/Menu.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<!------ Include the above in your HEAD tag ---------->
@*<header class="header" role="banner">
    <img src="~/img/Banner.png" /></header>*@

<nav class="navbar navbar-default" style="width:100%">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index","Home")" style="color:white">SANICENTER</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                @{

                    if (listamenucabecera.Count > 0)
                    {
                        foreach (Opcion item in listamenucabecera)
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>@item.Nombre</a>
                                <ul class="dropdown-menu">
                                    @foreach (Opcion submenu in listadomenuitems)
                                    {
                                        if (item.Id.Equals(submenu.IdMenu))
                                        {
                                            if (submenu.Nombre == "Apertura / Cierre de Caja")
                                            {
                                                <li>
                                                    <a href="@Url.Action("Index","Caja")">
                                                        <span aria-hidden="true"></span>
                                                        @submenu.Nombre
                                                    </a>
                                                </li>
                                            }
                                            else if (submenu.Nombre == "Facturación")
                                            {
                                                <li>
                                                    <a href="@Url.Action("Facturación","Caja")">
                                                        <span aria-hidden="true"></span>
                                                        @submenu.Nombre
                                                    </a>
                                                </li>
                                            }
                                        }
                                    }
                                </ul>
                            </li>
                        }
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Usuario<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="" target="_blank"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> User Settings</a></li>
                        <li><a href="@Url.Action("IniciarSesion","Seguridad")"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>


@*LLENAR EL TIPO DE CAMBIO*@
<div class="crumbs" style="width:100%;">
    <ul id="breadcrumbs" class="breadcrumb">
        <li>
            <i class="icon-home"></i>
            <label>Tienda: PALAO 9</label>
        </li>
        <li>
            <label>T.C.SUNAT($):3.302</label>
        </li>
        <li>
            <label>T.C.INTERNO($):3.280</label>
        </li>
        <li>
            <a href="#" title="">
                <i class="icon-calendar"></i>
                <span>@DateTime.Now.ToString("dddd, dd MMMM yyyy")</span>
            </a>
        </li>
    </ul>
</div>

SaniCenterWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - SIGE</title>    
    @Styles.Render("~/Content/css")

    @Scripts.Render("~/Content/js")
</head>
<body>
    @Html.Partial("_Header")    
    <div class="body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sanicenter</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

SaniCenterWeb/Views/Shared/_PuntodeLlegada.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Punto de Llegada</h3>
                <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
            </div>
            <div class="panel-body">
                <div class="row" style="margin-top:10px;">
                    <div class="col-md-2">
                        <label class="control-label">
                            Departamento:
                        </label>
                    </div>
                    <div class="col-md-2">
                        <select class="form-control" ID="cbodepartamentollegada"></select>
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">
                            Provincia:
                        </label>
                    </div>
                    <div class="col-md-2">
                        <select class="form-control" ID="cboProvinciallegada"></select>
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">
                            Distrito:
                        </label>
                    </div>
                    <div class="col-md-2">
                        <select class="form-control" ID="cboDistritollegada"></select>
                    </div>
                </div>
                <div class="row" style="margin-top:10px;">
                    <div class="col-md-2">
                        <label class="control-label">
                            Dirección:
                        </label>
                    </div>
                    <div class="col-md-10">
                        <input type="text" class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SaniCenterWeb/Views/Shared/_PuntodePartida.cshtml
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Punto de Partida</h3>
                <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span>
            </div>
            <div class="panel-body">
                <div class="row" style="margin-top:10px;">
                    <div class="col-md-2">
                        <label class="control-label">
                            Departamento:
                        </label>
                    </div>
                    <div class="col-md-2">
                        <select class="form-control" ID="cbodepartamentopartida"></select>
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">
                            Provincia:
                        </label>
                    </div>
                    <div class="col-md-2">
                        <select class="form-control" ID="cboProvinciapartida"></select>
                    </div>
                    <div class="col-md-2">
                        <label class="control-label">
                            Distrito:
                        </label>
                    </div>
                    <div class="col-md-2">
                        <select class="form-control" ID="cboDistritopartida"></select>
                    </div>
                </div>
                <div class="row" style="margin-top:10px;">
                    <div class="col-md-2">
                        <label class="control-label">
                            Dirección:
                        </label>
                    </div>
                    <div class="col-md-10">
                        <input type="text" class="form-control" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>